// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtRI9lPe3hDWVcbFwtyfEXw8rHnBBNFo0',
    appId: '1:830017708682:web:placeholder',
    messagingSenderId: '830017708682',
    projectId: 'uzme-app',
    authDomain: 'uzme-app.firebaseapp.com',
    storageBucket: 'uzme-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtRI9lPe3hDWVcbFwtyfEXw8rHnBBNFo0',
    appId: '1:830017708682:android:edfc9be7eb65684dda0373',
    messagingSenderId: '830017708682',
    projectId: 'uzme-app',
    storageBucket: 'uzme-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI1EK7Se-iNCB428RtWZ0mhgZ_6jUOMFw',
    appId: '1:830017708682:ios:a24c8ee86f9c8641da0373',
    messagingSenderId: '830017708682',
    projectId: 'uzme-app',
    storageBucket: 'uzme-app.firebasestorage.app',
    androidClientId: '830017708682-l5976rfnqen0ap7ofmhn6adb7bt6p4j3.apps.googleusercontent.com',
    iosClientId: '830017708682-f4sl6lpjhu1ca9dpbfbv40r5jlbvqrls.apps.googleusercontent.com',
    iosBundleId: 'com.smoothandesign.useme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI1EK7Se-iNCB428RtWZ0mhgZ_6jUOMFw',
    appId: '1:830017708682:ios:a24c8ee86f9c8641da0373',
    messagingSenderId: '830017708682',
    projectId: 'uzme-app',
    storageBucket: 'uzme-app.firebasestorage.app',
    androidClientId: '830017708682-l5976rfnqen0ap7ofmhn6adb7bt6p4j3.apps.googleusercontent.com',
    iosClientId: '830017708682-f4sl6lpjhu1ca9dpbfbv40r5jlbvqrls.apps.googleusercontent.com',
    iosBundleId: 'com.smoothandesign.useme',
  );
}
