// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcZKj-FD4aRyp6Nmmi38v0hVKOpYwyU_k',
    appId: '1:1053737369070:web:19904e4f41bf63ef6422ff',
    messagingSenderId: '1053737369070',
    projectId: 'smoothandesign',
    authDomain: 'smoothandesign.firebaseapp.com',
    databaseURL: 'https://smoothandesign-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smoothandesign.appspot.com',
    measurementId: 'G-NVQBYQ0DRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf1fPBEucMKCM-zxt3zEXxBzHSKqdEmLs',
    appId: '1:1053737369070:android:677caa34632001ec6422ff',
    messagingSenderId: '1053737369070',
    projectId: 'smoothandesign',
    databaseURL: 'https://smoothandesign-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smoothandesign.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ4Hpc-0F-1xr9e0VqYg5sF9NOTbqIpHU',
    appId: '1:1053737369070:ios:f4fe4935346b0bf46422ff',
    messagingSenderId: '1053737369070',
    projectId: 'smoothandesign',
    databaseURL: 'https://smoothandesign-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smoothandesign.appspot.com',
    androidClientId: '1053737369070-0n3f4c9k1hmmcsovpritl9sp251cn81v.apps.googleusercontent.com',
    iosClientId: '1053737369070-akmcqtcto4449fq8s1l8oke6r486gfp1.apps.googleusercontent.com',
    iosBundleId: 'com.smoothandesign.useme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ4Hpc-0F-1xr9e0VqYg5sF9NOTbqIpHU',
    appId: '1:1053737369070:ios:f4fe4935346b0bf46422ff',
    messagingSenderId: '1053737369070',
    projectId: 'smoothandesign',
    databaseURL: 'https://smoothandesign-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smoothandesign.appspot.com',
    androidClientId: '1053737369070-0n3f4c9k1hmmcsovpritl9sp251cn81v.apps.googleusercontent.com',
    iosClientId: '1053737369070-akmcqtcto4449fq8s1l8oke6r486gfp1.apps.googleusercontent.com',
    iosBundleId: 'com.smoothandesign.useme',
  );
}
